### ISSUE TITLE
배열

### ISSUE THREAD

**Issue by cri-kim** [cri-kim/build-knowledge-team#11]
# 배열
## 목차
- [두 수의 합](https://leetcode.com/problems/two-sum/)
- [빗물 트래핑](https://leetcode.com/problems/trapping-rain-water/)
- [세 수의 합](https://leetcode.com/problems/3sum/)
- [배열 파티션 I](https://leetcode.com/problems/array-partition-i/)
- [자신을 제외한 배열의 곱](https://leetcode.com/problems/product-of-array-except-self/)
- [주식을 사고팔기 가장 좋은 시점](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/)
# 참고
- https://github.com/onlybooks/algorithm-interview
- leetcode
# 마감기한
> 2021년 11월 07일 23시 59분 까지

**Comment by sowonning** [comment]
Hi
